# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Home-Maintenance' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Home-Maintenance
  	pod 'VeloxDownloader', '~> 1.6'
	pod 'NXDrawKit'
	pod "EPSignature"
	pod 'NYTPhotoViewer', '~> 1.1.0'
  	pod 'MBProgressHUD', '~> 1.0.0'
  	pod 'IQKeyboardManagerSwift'
	pod 'SQLite.swift', '~> 0.11.4'
	pod 'JGProgressHUD'
	pod 'RSKImageCropper'
	pod "Dropper"
    pod 'IQKeyboardManagerSwift', '5.0.0'
    pod 'FSCalendar'
    pod 'PDFGenerator', '~> 2.1'
    pod 'Digger'
end
